services:
    trinity.messages.message_sender:
        class: Trinity\Bundle\MessagesBundle\Sender\MessageSender
        arguments:
            - "@event_dispatcher"
            - "%trinity.messages.sender_identification%"

    trinity.messages.message_reader:
        class: Trinity\Bundle\MessagesBundle\Reader\MessageReader
        arguments:
            - "@event_dispatcher"

    trinity.messages.message_subscriber:
        class: Trinity\Bundle\MessagesBundle\EventListener\MessageSubscriber
        arguments:
            - "@trinity.messages.message_reader"
        tags:
            - { name: kernel.event_subscriber }